# Dependencies
markdown:         kramdown
#redcarpet:
#  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
# http://stackoverflow.com/questions/16099153/table-not-render-when-use-redcarpet-in-jekyll-github-pages
highlighter:      rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title: 'ssh me@abhishek.gupta'
description: >
  Here I blog about I everything I learn.
  I am kind of amnesiac person. So I decided to blog everything I learn. Let see how it goes.
url: "http://knoxxs.github.io/" # the base hostname & protocol for your site
baseurl: ""

author:
  name:           'Abhishek Gupta'
  twitter_username: knoxxs
  github_username:  knoxxs
  email: abhi.bansal21@gmail.com

# Custom
github: https://github.com/knoxxs/knoxxs.github.io

# Issues

# 1. Invalid date post
# Error: https://travis-ci.org/knoxxs/knoxxs.github.io/builds/81470182
# Solution: https://github.com/jekyll/jekyll/issues/2938#issuecomment-56237068
exclude: [vendor]

# http://jekyllrb.com/docs/upgrading/2-to-3/#all-my-posts-are-gone-whered-they-go
# Email with subject: [knoxxs/knoxxs.github.io] Page build failure
future: true