# Site settings
title: Abhishek's blog
email: abhi.bansal21@gmail.com
description: > 
  Here I blog about I everything I learn.
  I am kind of amnesiac person. So I decided to blog everything I learn. Let see how it goes.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://knoxxs.github.io/" # the base hostname & protocol for your site
twitter_username: knoxxs
github_username:  knoxxs
highlighter: pygments
github: [Repository metadata]


# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
# http://stackoverflow.com/questions/16099153/table-not-render-when-use-redcarpet-in-jekyll-github-pages
