# Dependencies
markdown:         redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
# http://stackoverflow.com/questions/16099153/table-not-render-when-use-redcarpet-in-jekyll-github-pages
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title: 'ls /abhishek/life/'
description: >
  Here I blog about I everything I learn.
  I am kind of amnesiac person. So I decided to blog everything I learn. Let see how it goes.
url: "http://knoxxs.github.io/" # the base hostname & protocol for your site
baseurl: ""

author:
  name:           'Abhishek Gupta'
  twitter_username: knoxxs
  github_username:  knoxxs
  email: abhi.bansal21@gmail.com

# Custom
github: https://github.com/knoxxs/knoxxs.github.io